[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "fullscreen 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com https://polyfill.io https://platform.twitter.com https://cdn.syndication.twimg.com https://storage.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https://pixel.thesemetrics.xyz https://syndication.twitter.com; media-src 'self' data:; font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com; frame-src 'self' https://platform.twitter.com"
    X-Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com https://polyfill.io https://platform.twitter.com https://cdn.syndication.twimg.com https://storage.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https://pixel.thesemetrics.xyz https://syndication.twitter.com; media-src 'self' data:; font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com; frame-src 'self' https://platform.twitter.com"
    X-WebKit-CSP = "default-src 'self'; script-src 'self' https://unpkg.com https://polyfill.io https://platform.twitter.com https://cdn.syndication.twimg.com https://storage.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https://pixel.thesemetrics.xyz https://syndication.twitter.com; media-src 'self' data:; font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com; frame-src 'self' https://platform.twitter.com"