[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "fullscreen 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self' https://polyfill.io https://www.google-analytics.com https://platform.twitter.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data:; media-src 'self' data:; font-src 'self' https://fonts.googleapis.com; connect-src 'self' https://www.google-analytics.com"
    X-Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self' https://polyfill.io https://www.google-analytics.com https://platform.twitter.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data:; media-src 'self' data:; font-src 'self' https://fonts.googleapis.com; connect-src 'self' https://www.google-analytics.com"
    X-WebKit-CSP-Report-Only = "default-src 'self'; script-src 'self' https://polyfill.io https://www.google-analytics.com https://platform.twitter.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data:; media-src 'self' data:; font-src 'self' https://fonts.googleapis.com; connect-src 'self' https://www.google-analytics.com"
